### ISSUE TITLE
Integrated messaging (build the no notification by default) 

### ISSUE THREAD

**Issue by GreatTA1998** [GreatTA1998/intentions.life#1]

**Comment by verypopularguy** [comment]
So instead of having to check different messaging apps, the advantage of an ecosystem is that, new messages show up as unscheduled tasks on the todo

**Comment by nileshtrivedi** [comment]
Hey @GreatTA1998 Kudos for making this project and open-sourcing it! 👏 

Messaging would also help with sharing tasks and events. I currently use Microsoft ToDo only because it allows me to share todos (including repeating tasks) within my family.

This idea (combining messaging, todos and events) can be taken a lot further. You might have seen how [Habitica](https://habitica.com/) models tasks. I had noted down some thoughts [here](https://codeberg.org/nilesh/request-for-hacks/issues/1).

**Comment by GreatTA1998** [comment]
Thanks for sharing this well-thoughtout idea - I used to be a daily active user of Habitica in 2018 by the way. 

Right now to constrain the scope of the project, I can't focus on collaboration yet. But I hope some day we could revisit this.
